name: My Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout templayte
        uses: actions/checkout@v3
        with:
          repository: jatla991/maven-web-application
          ref: main

      - name: use - template
        uses: jatla991/maven-web-application/Template/action.yml@main
